/* Generated by build-ramsey.mjs. */
(() => {
'use strict';
/** Ramsey model in discrete time, per effective worker. Growth factors are gross. */
const RAMSEY_DEFAULTS = Object.freeze({alpha:1/3,gamma:1.02,n:1.01,delta:.08,theta:1,beta:.96,sigma:2,tax:0});
const f=(k,p)=>Math.pow(p.theta*k,p.alpha);
const mpk=(k,p)=>p.alpha*f(k,p)/k;
const netReturn=(k,p)=>1+(mpk(k,p)-p.delta)*(1-p.tax);
const utility=(c,sigma)=>sigma===1?Math.log(c):(Math.pow(c,1-sigma)-1)/(1-sigma);
function validateRamsey(p){
 if(!Object.values(p).every(Number.isFinite)||!(p.alpha>0&&p.alpha<1&&p.gamma>=1&&p.n>=1&&p.delta>0&&p.delta<1&&p.theta>0&&p.beta>0&&p.beta<1&&p.sigma>0&&p.tax>=0&&p.tax<=1))throw Error('Invalid Ramsey parameters');
 if(p.beta*p.n*Math.pow(p.gamma,1-p.sigma)>=1)throw Error('Discounted utility requires β n γ^(1−σ) < 1; lower β or n, or increase σ');
 if(!(Math.pow(p.gamma,p.sigma)/p.beta>1-p.delta))throw Error('No finite interior steady state');
}
const nextK=(k,c,p)=>(f(k,p)+(1-p.delta)*k-c)/(p.gamma*p.n);
const nextC=(c,kNext,p)=>c*Math.pow(p.beta*netReturn(kNext,p),1/p.sigma)/p.gamma;
const kNull=(k,p)=>f(k,p)-(p.delta+p.gamma*p.n-1)*k;
function steady(p){
 validateRamsey(p);
 if(p.tax===1)return {k:0,c:0,boundary:true};
 const target=p.delta+(Math.pow(p.gamma,p.sigma)/p.beta-1)/(1-p.tax);
 const k=Math.pow(p.alpha*Math.pow(p.theta,p.alpha)/target,1/(1-p.alpha));
 const c=kNull(k,p);
 if(!(c>0))throw Error('These parameters do not admit positive steady-state consumption');
 return {k,c,boundary:false};
}
/** Discrete-time consumption nullcline. It is curved because Euler uses k_(t+1). */
const cNull=(k,p)=>{const s=steady(p);return s.boundary?NaN:f(k,p)+(1-p.delta)*k-p.gamma*p.n*s.k;};
function inverseResource(value,p){
 let lo=0,hi=Math.max(1,value);
 while(f(hi,p)+(1-p.delta)*hi<value)hi*=2;
 for(let j=0;j<65;j++){const mid=(lo+hi)/2;if(f(mid,p)+(1-p.delta)*mid<value)lo=mid;else hi=mid;}
 return (lo+hi)/2;
}
function backward(kNext,cNext,p){
 const c=p.gamma*cNext/Math.pow(p.beta*netReturn(kNext,p),1/p.sigma);
 const k=inverseResource(c+p.gamma*p.n*kNext,p);
 return {k,c};
}
/** Stable manifold by inverse dynamics, seeded along the stable eigenvector. */
function saddle(p,minimum,maximum){
 const s=steady(p);if(s.boundary)return [];
 const R=netReturn(s.k,p),a=(mpk(s.k,p)+1-p.delta)/(p.gamma*p.n),b=-1/(p.gamma*p.n);
 const d=s.c*(1-p.tax)*(p.alpha-1)*mpk(s.k,p)/(s.k*p.sigma*R);
 const trace=a+1+d*b,det=a,disc=Math.max(0,trace*trace-4*det);
 const lambda=(trace-Math.sqrt(disc))/2,slope=(lambda-a)/b;
 // High taxes and large σ can make the stable root very close to one.
 // Resolve the requested capital range instead of stopping after a fixed 650 inverse steps.
 const distance=Math.max(maximum/s.k,s.k/Math.max(minimum,1e-12),2);
 const maxSteps=Math.min(20000,Math.max(650,3*Math.ceil(Math.log(distance/1e-5)/Math.max(1e-5,-Math.log(lambda)))));
 const points=[{k:s.k,c:s.c,slope}];
 for(const dir of [-1,1]){
  let point={k:s.k+dir*s.k*1e-5,c:s.c+dir*s.k*1e-5*slope,slope};
  const branch=[];
  for(let j=0;j<maxSteps && point.k>1e-12 && point.c>1e-12 && Number.isFinite(point.k+point.c);j++){
   branch.push(point);
   if((dir<0&&point.k<minimum)||(dir>0&&point.k>maximum))break;
   const older=backward(point.k,point.c,p);
   // Propagate the tangent through the inverse map for accurate Hermite interpolation.
   const derivative=(older.c/point.c)*point.slope-older.c*(1-p.tax)*(p.alpha-1)*mpk(point.k,p)/(point.k*p.sigma*netReturn(point.k,p));
   older.slope=(mpk(older.k,p)+1-p.delta)*derivative/(derivative+p.gamma*p.n);
   if(Math.abs(older.k-point.k)<1e-12*s.k)break;
   point=older;
  }
  points.push(...branch);
 }
 return points.sort((x,y)=>x.k-y.k);
}
function onManifold(k,points){
 let lo=0,hi=points.length-1;
 if(k<points[lo].k||k>points[hi].k)throw Error('Initial capital is outside the numerically resolved saddle path');
 if(k===points[lo].k)return points[lo].c;
 if(k===points[hi].k)return points[hi].c;
 while(hi-lo>1){const m=(lo+hi)>>1;if(points[m].k<k)lo=m;else hi=m;}
 const a=points[lo],b=points[hi],h=b.k-a.k,t=(k-a.k)/h,sec=(b.c-a.c)/h;
 // Cubic Hermite interpolation uses inverse-map tangents to reduce Euler error between samples.
 const slope=i=>{
  if(i<=0||i>=points.length-1)return sec;
  const left=(points[i].c-points[i-1].c)/(points[i].k-points[i-1].k);
  const right=(points[i+1].c-points[i].c)/(points[i+1].k-points[i].k);
  return left*right<=0?0:2*left*right/(left+right);
 };
 const m0=Number.isFinite(a.slope)?a.slope:slope(lo),m1=Number.isFinite(b.slope)?b.slope:slope(hi);
 return (2*t**3-3*t*t+1)*a.c+(t**3-2*t*t+t)*h*m0+(-2*t**3+3*t*t)*b.c+(t**3-t*t)*h*m1;
}
/** Boundary case at tax=100%: finite-horizon shooting approximates the path to zero. */
function boundaryConsumption(k,p,remaining){
 let lo=0,hi=f(k,p)+(1-p.delta)*k;
 const terminal=c0=>{
  let capital=k,consumption=c0;
  for(let j=0;j<remaining;j++){
   const next=nextK(capital,consumption,p);
   if(!(next>0))return -1;
   capital=next;consumption=nextC(consumption,next,p);
   if(!Number.isFinite(capital))return 1;
  }
  return capital;
 };
 // High consumption exhausts resources; search for the near-zero terminal stock.
 for(let j=0;j<65;j++){const m=(lo+hi)/2;if(terminal(m)>1e-8)lo=m;else hi=m;}
 return (lo+hi)/2;
}
function observation(t,k,c,A,N,p){
 const y=f(k,p),i=y-c;
 return {t,k,c,y,i,s:i/y,r:mpk(k,p),w:(1-p.alpha)*A*y,A,N,p};
}
function consumptionAt(k,p,manifold,remaining){
 return p.tax===1?boundaryConsumption(k,p,remaining+30):onManifold(k,manifold);
}
/** Solve the announced transition as a boundary-value problem, not unstable forward shooting.
 * Unknowns are k_1,...,k_T. Each Euler residual touches only adjacent capital stocks.
 * The terminal consumption is on the post-policy stable manifold. */
function announcedPrefix(before,after,k0,shock,horizon,pre,post){
 const G=before.gamma*before.n;
 const capitals=[k0];
 for(let t=0;t<shock;t++){
  const c=consumptionAt(capitals[t],before,pre,horizon-t);
  capitals.push(nextK(capitals[t],c,before));
 }
 const terminal=k=>consumptionAt(k,after,post,horizon-shock);
 const evaluate=(ks,jacobian=false)=>{
  if(ks.some(k=>!(k>1e-14&&Number.isFinite(k))))return null;
  let tail;try{tail=terminal(ks[shock]);}catch{return null;}
  const cs=ks.slice(0,-1).map((k,t)=>f(k,before)+(1-before.delta)*k-G*ks[t+1]);cs.push(tail);
  if(cs.some(c=>!(c>1e-14&&Number.isFinite(c))))return null;
  const residual=[],lower=[],diagonal=[],upper=[];
  for(let t=0;t<shock;t++){
   const k=ks[t+1],R=netReturn(k,before);
   residual.push(Math.log(cs[t+1]/cs[t])-(Math.log(before.beta*R)/before.sigma-Math.log(before.gamma)));
   if(jacobian){
    let derivative;
    if(t===shock-1){
     const h=Math.max(1e-10,k*1e-5);
     derivative=(terminal(k+h)-terminal(Math.max(k*.5,k-h)))/(k+h-Math.max(k*.5,k-h));
    }else derivative=mpk(k,before)+1-before.delta;
    const eulerDerivative=(1-before.tax)*(before.alpha-1)*mpk(k,before)/(k*before.sigma*R);
    lower.push(t?-(mpk(ks[t],before)+1-before.delta)/cs[t]:0);
    diagonal.push(derivative/cs[t+1]+G/cs[t]-eulerDerivative);
    upper.push(t<shock-1?-G/cs[t+1]:0);
   }
  }
  return {cs,residual,lower,diagonal,upper,norm:Math.max(...residual.map(Math.abs))};
 };
 for(let iteration=0;iteration<75;iteration++){
  const state=evaluate(capitals,true);
  if(!state)throw Error('The announced transition has no feasible starting point');
  if(state.norm<2e-10)return {capitals,consumption:state.cs};
  const {lower,diagonal,upper}=state,rhs=state.residual.map(v=>-v);
  for(let j=1;j<shock;j++){
   const ratio=lower[j]/diagonal[j-1];diagonal[j]-=ratio*upper[j-1];rhs[j]-=ratio*rhs[j-1];
  }
  const step=Array(shock);step[shock-1]=rhs[shock-1]/diagonal[shock-1];
  for(let j=shock-2;j>=0;j--)step[j]=(rhs[j]-upper[j]*step[j+1])/diagonal[j];
  let accepted=false;
  for(let scale=1;scale>=2**-24;scale*=.5){
   const trial=[k0,...step.map((d,j)=>capitals[j+1]+scale*d)];
   const candidate=evaluate(trial);
   if(candidate&&candidate.norm<state.norm){capitals.splice(0,capitals.length,...trial);accepted=true;break;}
  }
  if(!accepted)throw Error('The announced transition could not be resolved; reduce the shock size');
 }
 throw Error('The announced transition did not reach numerical tolerance');
}
/** Forward Euler dynamics deliberately do not project deviations back onto the saddle path. */
function unstableRamsey(before,after,optimal,shock,horizon,deviation=0,anticipated=false){
 const rows=[];let k=optimal[0].k,c=optimal[0].c*(1+deviation),A=1,N=1,termination=null;
 for(let t=0;t<=horizon;t++){
  const p=t<shock?before:after;
  if(!(k>0&&c>0&&Number.isFinite(k+c))){termination='Consumption approaches zero';break;}
  const capital=nextK(k,c,p);
  rows.push(observation(t,k,c,A,N,p));
  if(!(capital>0&&Number.isFinite(capital))){termination='Capital is exhausted';break;}
  if(t===horizon)break;
  let consumption=nextC(c,capital,p);
  if(!anticipated&&t+1===shock){
   const expected=nextC(optimal[t].c,optimal[t+1].k,before);
   consumption*=optimal[t+1].c/expected;
  }
  k=capital;c=consumption;A*=p.gamma;N*=p.n;
 }
 return {rows,termination};
}
/** TVC is an asymptotic condition. Interior stable paths satisfy it analytically:
 * (β n γ^(1−σ))^T k_(T+1)/c_T^σ tends to zero on the BGP.
 * Finite-horizon boundary paths are explicitly reported as approximations. */
function ramseyDiagnostic(after,deviation,termination=null){
 if(Math.abs(deviation)>1e-10)return {
  status:deviation<0?'violated':'diverging',
  label:deviation<0?'TVC violated: excess accumulation':'Path does not converge',
  detail:termination||'Initial consumption misses the unique stable path; the Euler trajectory is not projected back.'
 };
 if(after.tax===1)return {status:'boundary',label:'Boundary path: TVC is approximated',detail:'100% tax has no positive steady state. This is a finite-horizon boundary solution.'};
 return {status:'satisfied',label:`${after.tax>0?'Equilibrium':'Optimal'} path: TVC satisfied ✓`,detail:'The stable continuation converges to the balanced-growth path, where β n γ^(1−σ) < 1. The diagnostic uses this asymptotic continuation, not a finite endpoint alone.'};
}
function simulateRamsey(before,after,k0,shock=20,horizon=160,options={}){
 validateRamsey(before);validateRamsey(after);
 if(!(k0>0&&Number.isFinite(k0)&&Number.isInteger(shock)&&shock>=1&&Number.isInteger(horizon)&&horizon>=shock))throw Error('Invalid dates or initial capital');
 const lower=Math.max(1e-5,Math.min(k0,steady(before).k||k0,steady(after).k||k0)*.15);
 const upper=Math.max(k0,steady(before).k,steady(after).k)*2.5;
 const pre=saddle(before,lower,upper),post=saddle(after,lower,upper);
 const anticipated=Boolean(options.anticipated),deviation=options.consumptionDeviation??0;
 if(!(Number.isFinite(deviation)&&deviation>=-.5&&deviation<=.5))throw Error('Initial consumption deviation must be between −50% and 50%');
 const changed=Object.keys(before).some(key=>Math.abs(before[key]-after[key])>1e-12);
 const prefix=anticipated&&changed?announcedPrefix(before,after,k0,shock,horizon,pre,post):null;
 let k=k0,A=1,N=1;
 const rows=[];
 for(let t=0;t<=horizon;t++){
  const p=t<shock?before:after,manifold=t<shock?pre:post;
  if(prefix&&t<=shock)k=prefix.capitals[t];
  const c=prefix&&t<shock?prefix.consumption[t]:consumptionAt(k,p,manifold,horizon-t);
  if(!(c>0&&c<f(k,p)+(1-p.delta)*k))throw Error('Capital outside the feasible saddle path');
  rows.push(observation(t,k,c,A,N,p));
  if(t<horizon){k=nextK(k,c,p);if(!(k>0&&Number.isFinite(k)))throw Error('Capital path is infeasible');A*=p.gamma;N*=p.n;}
 }
 const alternative=deviation?unstableRamsey(before,after,rows,shock,horizon,deviation,anticipated):null;
 return {rows:alternative?alternative.rows:rows,optimal:rows,pre,post,
  termination:alternative?.termination||null,diagnostic:ramseyDiagnostic(after,deviation,alternative?.termination)};
}

/* UI source. build-ramsey.mjs combines this with ramsey-model.js for the browser. */
function initializeRamsey() {
 const $ = id => {
  const node = document.getElementById(id);
  if (!node) throw Error(`Missing Ramsey element: ${id}`);
  return node;
 };
 const workspace = $('ramsey-workspace');
 const colors = {teal:'#087d73',base:'#8d9fa6',amber:'#be7a24',grid:'#e9efed',muted:'#82918c',k:'#467da0',c:'#7956a3',unstable:'#bd5866'};
 const specs = [
  ['beta','\\beta','Discount factor',.85,.995,.001,'r-preferences'],
  ['sigma','\\sigma','Utility curvature',.5,5,.05,'r-preferences'],
  ['alpha','\\alpha','Capital share',.15,.65,.01,'r-technology'],
  ['gamma','\\gamma','Technology growth',1,1.06,.001,'r-technology'],
  ['n','n','Population growth',1,1.04,.001,'r-technology'],
  ['delta','\\delta','Depreciation',.01,.25,.005,'r-technology'],
  ['theta','\\theta','Capital augmentation',.5,2,.05,'r-technology'],
  ['tax','\\tau','Capital income tax',0,1,.01,'r-policy']
 ];
 const charts = [['k','Capital','k_t'],['K','Total capital','K_t'],['y','Output','y_t'],['Y','Total output','Y_t'],['c','Consumption','c_t'],['C','Total consumption','C_t'],['r','Capital return','r_t'],['w','Wage','w_t'],['s','Saving rate','s_t=i_t/y_t'],['i','Investment','i_t=y_t-c_t'],['u','Utility','u(\\tilde c_t)']];
 const pairs = [['Capital','k','K'],['Output','y','Y'],['Consumption','c','C'],['Returns & wages','r','w'],['Savings','s','i'],['Utility & economy','u',null]];
 let before={...RAMSEY_DEFAULTS},after={...RAMSEY_DEFAULTS},k0=steady(before).k,locked=true;
 let mode='after',tau=20,horizon=160,time=0,playing=false,lastFrame=0,dirty=true,zoomKey='phase';
 let rows=[],optimal=[],baseline=[],pre=[],post=[],impact=null,bounds={k:1,c:1},diagnostic=null;
 let anticipated=false,showUnstable=false,consumptionDeviation=0,unstablePaths=[],endTime=horizon;
 let jumpActive=false,jumpProgress=1;
 const different = () => specs.some(([key])=>Math.abs(before[key]-after[key])>1e-10);
 const format = v => Math.abs(v)>=1e5?v.toExponential(2):v.toLocaleString('en-US',{maximumFractionDigits:3,minimumFractionDigits:3});
 const tick = v => Math.abs(v)>=1e4?v.toExponential(1):Math.abs(v)>=100?String(Math.round(v)):Math.abs(v)>=10?v.toFixed(1):v.toFixed(2);
 const chartValue = (r,key) => key==='u'?utility(r.A*r.c,r.p.sigma):['K','Y','C'].includes(key)?r[key.toLowerCase()]*r.A*r.N:r[key];
 const hasJump = () => different()&&!anticipated;
 const displayValue = (value,key) => key==='s'?`${(100*value).toFixed(1)}%`:format(value);
 const fill = node => node.style.setProperty('--fill',`${100*(+node.value-+node.min)/(+node.max-+node.min)}%`);
 function typeset(root) {
  if (!window.katex) return;
  root.querySelectorAll('[data-tex]').forEach(node=>window.katex.render(node.dataset.tex,node,{throwOnError:false}));
 }
 function listen(id,event,callback) {
  $(id).addEventListener(event,e=>{
   try { callback(e); }
   catch(error) { pause(); $('r-insight').textContent=error.message; console.error(error); }
  });
 }
 function pause() {
  playing=false;jumpActive=false;jumpProgress=1;dirty=true;
  $('r-play').textContent=$('r-zoom-play').textContent='▶ Play';
 }
 function play() {
  if(time>=endTime)time=0;
  playing=true;lastFrame=performance.now();
  $('r-play').textContent=$('r-zoom-play').textContent='Ⅱ Pause';
 }
 function build() {
  $('r-rows').replaceChildren();
  for(const [name,left,right] of pairs) {
   const section=document.createElement('details');section.className='r-row';
   section.open=name==='Capital'||name==='Consumption';
   const card=key=>{
    if(!key)return '<section class="response r-live"><div class="plot-heading"><h2>Live economy</h2><span id="r-live-t"></span></div><div class="metrics"><div><span data-tex="A_t"></span><strong id="r-A"></strong></div><div><span data-tex="N_t"></span><strong id="r-N"></strong></div></div><div id="r-growth" class="growth-readout"></div></section>';
    const [,title,symbol]=charts.find(x=>x[0]===key);
    return `<section class="response"><div class="plot-heading"><h2>${title} <span data-tex="${symbol}"></span></h2><output id="r-value-${key}"></output><button type="button" class="chart-zoom" data-r-zoom="${key}" aria-label="Enlarge ${title} graph">↗</button></div><div class="mini-frame"><canvas id="r-chart-${key}" role="img" aria-label="${title} over time"></canvas></div></section>`;
   };
   section.innerHTML=`<summary>${name}<span>⌄</span></summary><div class="r-row-content">${card(left)}${card(right)}</div>`;
   $('r-rows').append(section);
   section.addEventListener('toggle',()=>dirty=true);
  }
  for(const group of ['r-preferences','r-technology','r-policy'])$(group).replaceChildren();
  for(const [key,symbol,title,min,max,step,group] of specs) {
   const div=document.createElement('div');div.className='slider';
   div.innerHTML=`<div class="slider-head"><label for="r-param-${key}"><span data-tex="${symbol}"></span><span>${title}</span></label><output id="r-out-${key}"></output></div><input id="r-param-${key}" type="range" min="${min}" max="${max}" step="${step}" aria-label="${title}">`;
   $(group).append(div);
   listen(`r-param-${key}`,'input',e=>change(()=>{(mode==='before'?before:after)[key]=+e.target.value;},mode==='before'||anticipated?0:tau-1));
  }
  workspace.querySelectorAll('[data-r-zoom]').forEach(button=>button.addEventListener('click',()=>openZoom(button.dataset.rZoom)));
  typeset(workspace);typeset($('r-zoom'));typeset($('r-model-dialog'));
 }
 function recompute() {
  const shocked=simulateRamsey(before,after,k0,tau,horizon,{anticipated,consumptionDeviation});
  const control=simulateRamsey(before,before,k0,tau,horizon);
  rows=shocked.rows;optimal=shocked.optimal;baseline=control.rows;pre=shocked.pre;post=shocked.post;diagnostic=shocked.diagnostic;endTime=rows.at(-1).t;
  impact=baseline[tau];
  if(consumptionDeviation&&hasJump()&&rows[tau]){
   const x=rows[tau-1];impact={...rows[tau],c:nextC(x.c,rows[tau].k,before),p:before};
   impact.y=f(impact.k,before);impact.i=impact.y-impact.c;impact.s=impact.i/impact.y;impact.r=mpk(impact.k,before);impact.w=(1-before.alpha)*impact.A*impact.y;
  }
  unstablePaths=[-.025,.025].map(deviation=>({deviation,...unstableRamsey(before,after,optimal,tau,horizon,deviation,anticipated)}));
  // Keep a useful phase scale even when a deliberately unstable path leaves the neighborhood.
  bounds.k=Math.max(k0,steady(before).k,steady(after).k,...optimal.map(r=>r.k))*1.42;
  bounds.c=Math.max(...optimal.map(r=>r.c),...baseline.map(r=>r.c),kNull(bounds.k*.6,before),kNull(bounds.k*.6,after))*1.4;
  $('r-tvc').textContent=diagnostic.label;$('r-tvc').dataset.status=diagnostic.status;$('r-tvc').title=diagnostic.detail;
  $('r-insight').textContent=consumptionDeviation?`${diagnostic.label}. ${diagnostic.detail}`:after.tax===1?'100% tax removes the positive interior steady state. The path approaches the zero-capital boundary.':different()?anticipated?`Policy is announced at t = 0: consumption adjusts immediately. The nullclines change only when policy takes effect at t = ${tau}.`:`At t = ${tau}, consumption jumps while capital is predetermined, then the economy follows the new saddle path.`:'The stable saddle path pins down c₀ given k₀. Toggle nearby paths or adjust c₀ to see why the other Euler paths do not converge.';
  dirty=true;
 }
 function sync() {
  const p=mode==='before'?before:after;
  for(const [key] of specs) {
   const slider=$(`r-param-${key}`);slider.value=p[key];fill(slider);
   $(`r-out-${key}`).textContent=['alpha','delta','tax'].includes(key)?`${(100*p[key]).toFixed(1)}%`:format(p[key]);
   slider.setAttribute('aria-valuetext',$(`r-out-${key}`).textContent);
  }
  for(const [id,selected] of [['r-before',mode==='before'],['r-after',mode==='after'],['r-growth-none',p.gamma===1&&p.n===1],['r-growth-positive',Math.abs(p.gamma-1.02)<1e-10&&Math.abs(p.n-1.01)<1e-10]]) {
   $(id).classList.toggle('selected',selected);$(id).setAttribute('aria-pressed',String(selected));
  }
  $('r-k0').value=Number(k0.toPrecision(8));
  $('r-steady').textContent=locked?'✓ At initial steady state':'Set to initial steady state';
  $('r-steady').disabled=before.tax===1;
  $('r-tau').value=tau;$('r-tau').max=horizon-1;$('r-horizon').value=horizon;
  $('r-time').max=endTime;$('r-shock-date').textContent=`Policy at ${tau}`;
  for(const [id,selected] of [['r-unanticipated',!anticipated],['r-anticipated',anticipated],['r-unstable',showUnstable]]){
   $(id).classList.toggle('selected',selected);$(id).setAttribute('aria-pressed',String(selected));
  }
  $('r-c0-deviation').value=100*consumptionDeviation;fill($('r-c0-deviation'));
  $('r-c0-offset').textContent=`${consumptionDeviation>0?'+':''}${(100*consumptionDeviation).toFixed(1)}%`;
  $('r-optimal-c0').textContent=format(optimal[0].c);dirty=true;
 }
 function change(edit,at=0) {
  pause();const saved={before:{...before},after:{...after},k0,locked,mode,tau,horizon,time,anticipated,consumptionDeviation,showUnstable};
  try {
   edit();if(locked){const initial=steady(before);if(initial.boundary)locked=false;else k0=initial.k;}
   recompute();time=Math.min(endTime,Math.max(0,at));sync();return true;
  } catch(error) {
   ({before,after,k0,locked,mode,tau,horizon,time,anticipated,consumptionDeviation,showUnstable}=saved);recompute();sync();
   $('r-insight').textContent=`${error.message}. Your previous feasible setting is retained.`;return false;
  }
 }
 function blend(a,b,fraction) {
  const result={...a};
  for(const key of ['k','c','y','i','s','r','w','A','N'])result[key]=a[key]+fraction*(b[key]-a[key]);
  return result;
 }
 function current() {
  if(jumpActive)return blend(impact,rows[tau],jumpProgress);
  const whole=Math.min(endTime,Math.floor(time)),a=rows[whole];
  const b=hasJump()&&whole+1===tau?impact:rows[Math.min(endTime,whole+1)];
  return blend(a,b,time-whole);
 }
 function surface(id) {
  const node=$(id),rect=node.getBoundingClientRect();
  if(rect.width<2||rect.height<2)return null;
  const dpr=window.devicePixelRatio||1,w=rect.width,h=rect.height;
  if(node.width!==Math.round(w*dpr)||node.height!==Math.round(h*dpr)){node.width=Math.round(w*dpr);node.height=Math.round(h*dpr);}
  const ctx=node.getContext('2d');if(!ctx)return null;
  ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.lineJoin='round';ctx.lineCap='round';
  return {ctx,w,h};
 }
 function line(ctx,points,color,width=1.5,dash=[]) {
  ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);
  let started=false;
  for(const [x,y] of points){if(!Number.isFinite(x+y)){started=false;continue;}if(started)ctx.lineTo(x,y);else ctx.moveTo(x,y);started=true;}
  ctx.stroke();ctx.setLineDash([]);
 }
 function dot(ctx,x,y,color,r=4) {ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=1.5;ctx.stroke();}
 function label(ctx,text,x,y,color=colors.muted,align='left',size=10) {ctx.fillStyle=color;ctx.font=`${size}px Arial`;ctx.textAlign=align;ctx.fillText(text,x,y);}
 function arrow(ctx,x1,y1,x2,y2,color,width=1.5) {
  line(ctx,[[x1,y1],[x2,y2]],color,width);
  const length=Math.hypot(x2-x1,y2-y1);if(length<6)return;
  const angle=Math.atan2(y2-y1,x2-x1),x=x1+.76*(x2-x1),y=y1+.76*(y2-y1),size=Math.min(5,length*.35);
  line(ctx,[[x-size*Math.cos(angle-.55),y-size*Math.sin(angle-.55)],[x,y],[x-size*Math.cos(angle+.55),y-size*Math.sin(angle+.55)]],color,width);
 }
 function phase(id='r-phase') {
  const canvas=surface(id);if(!canvas)return;
  const {ctx,w,h}=canvas,L=44,T=18,pw=Math.max(1,w-L-15),ph=Math.max(1,h-T-30);
  const X=k=>L+k/bounds.k*pw,Y=c=>T+ph-c/bounds.c*ph;
  for(let j=0;j<=4;j++){const k=j*bounds.k/4,c=j*bounds.c/4;line(ctx,[[X(k),T],[X(k),T+ph]],colors.grid,1);line(ctx,[[L,Y(c)],[L+pw,Y(c)]],colors.grid,1);label(ctx,tick(k),X(k),h-9,colors.muted,'center');label(ctx,tick(c),L-7,Y(c)+3,colors.muted,'right');}
  line(ctx,[[L,T],[L,T+ph],[L+pw,T+ph]],'#bccac5',1);
  ctx.save();ctx.beginPath();ctx.rect(L,T,pw,ph);ctx.clip();
  const regime=(p,arm,color,opacity)=>{
   const target=steady(p),sample=fn=>Array.from({length:240},(_,j)=>{const k=bounds.k*j/239;return [X(k),Y(fn(k))];});
   ctx.globalAlpha=opacity;
   line(ctx,sample(k=>kNull(k,p)),colors.k,1.8,[7,4]);
   if(!target.boundary)line(ctx,sample(k=>f(k,p)+(1-p.delta)*k-p.gamma*p.n*target.k),colors.c,1.8,[2,4]);
   line(ctx,arm.map(r=>[X(r.k),Y(r.c)]),color,2.9);ctx.globalAlpha=1;
  };
  const active=time<tau?before:after;
  const policyEffective=different()&&time>=tau;
  regime(before,pre,policyEffective?colors.base:colors.teal,policyEffective?.25:1);
  if(policyEffective)regime(after,post,colors.teal,1);
  if(showUnstable)for(const path of unstablePaths){
   const visible=path.rows.filter(r=>policyEffective?r.t>=tau:true);
   line(ctx,visible.map(r=>[X(r.k),Y(r.c)]),colors.unstable,1.5,[5,4]);
   for(let j=1;j<visible.length;j+=6)arrow(ctx,X(visible[j-1].k),Y(visible[j-1].c),X(visible[j].k),Y(visible[j].c),colors.unstable,1.4);
  }
  for(let col=1;col<=8;col++)for(let row=1;row<=6;row++) {
   const k=bounds.k*col/9,c=bounds.c*row/7,k1=nextK(k,c,active);if(!(k1>0))continue;
   const c1=nextC(c,k1,active),vx=(k1-k)/bounds.k*pw,vy=-(c1-c)/bounds.c*ph,length=Math.hypot(vx,vy);
   if(length<1e-6||!Number.isFinite(length))continue;
   const dx=vx/length*16,dy=vy/length*16;
   arrow(ctx,X(k)-dx/2,Y(c)-dy/2,X(k)+dx/2,Y(c)+dy/2,'#a5b5ad',1.2);
  }
  const whole=Math.floor(time),start=Math.max(0,whole-30),points=[];
  for(let t=start;t<=whole;t++){if(t===tau&&hasJump())points.push(impact);if(t===tau&&jumpActive)break;points.push(rows[t]);}
  points.push(current());
  for(let j=1;j<points.length;j++){ctx.globalAlpha=.25+.65*j/points.length;arrow(ctx,X(points[j-1].k),Y(points[j-1].c),X(points[j].k),Y(points[j].c),colors.amber,2.2);}
  ctx.globalAlpha=1;
  const old=steady(before),target=steady(after);
  if(!old.boundary)dot(ctx,X(old.k),Y(old.c),different()?colors.base:colors.teal,5);
  if(policyEffective)dot(ctx,X(target.k),Y(target.c),colors.teal,5);
  const now=current();dot(ctx,X(now.k),Y(now.c),colors.amber,5.5);ctx.restore();
  if(X(old.k)<L+pw&&Y(old.c)>T)label(ctx,different()?'Initial steady state':'Steady state',X(old.k)-8,Y(old.c)-11,policyEffective?colors.base:colors.teal,'right');
  if(policyEffective)label(ctx,target.boundary?'Zero-capital boundary':'New steady state',Math.min(L+pw-6,X(target.k)+8),Math.min(T+ph-6,Y(target.c)+18),colors.teal);
  const arm=policyEffective?post:pre;
  const anchor=arm.filter(r=>r.k>bounds.k*.42&&r.k<bounds.k*.65&&r.c<bounds.c*.8).at(0);
  if(anchor)label(ctx,'Stable saddle path',X(anchor.k)+5,Y(anchor.c)-10,colors.teal,'left',11);
  if(showUnstable)label(ctx,'Nearby Euler paths: c₀ ± 2.5%',L+8,T+14,colors.unstable,'left',10);
 }
 function series(id,key) {
  const canvas=surface(id);if(!canvas)return;
  const {ctx,w,h}=canvas,L=['K','Y','C'].includes(key)?48:42,T=8,pw=Math.max(1,w-L-15),ph=Math.max(1,h-T-20);
  const values=rows.map(r=>chartValue(r,key)).concat(baseline.map(r=>chartValue(r,key)));
  const lo=Math.min(...values),hi=Math.max(...values),span=Math.max(hi-lo,Math.abs(hi)*.15,.01);
  const min=lo<0?lo-span*.15:Math.max(0,lo-span*.15),max=hi+span*.15,X=t=>L+t/horizon*pw,Y=v=>T+(max-v)/(max-min)*ph;
  for(let j=0;j<(ph<60?2:3);j++){const v=min+(max-min)*j/(ph<60?1:2);line(ctx,[[L,Y(v)],[L+pw,Y(v)]],colors.grid,1);label(ctx,key==='s'?`${(100*v).toFixed(0)}%`:tick(v),L-6,Y(v)+3,colors.muted,'right',9);}
  for(const t of [0,horizon/2,horizon])label(ctx,String(t),X(t),h-5,colors.muted,'center',9);label(ctx,'t',w-1,h-5,colors.muted,'right');
  ctx.save();ctx.beginPath();ctx.rect(L,T,pw,ph);ctx.clip();
  if(different()){ctx.fillStyle='#f8f4eb';ctx.fillRect(X(tau),T,pw*(1-tau/horizon),ph);}
  line(ctx,baseline.map(r=>[X(r.t),Y(chartValue(r,key))]),colors.base,1.3,[4,4]);
  const points=rows.map(r=>[r.t,chartValue(r,key)]);if(hasJump()&&tau<=endTime)points.splice(tau,0,[tau,chartValue(impact,key)]);
  line(ctx,points.map(([t,v])=>[X(t),Y(v)]),colors.teal,1.4,[3,4]);
  const past=points.filter(([t])=>jumpActive?t<time:t<=time);
  if(jumpActive)past.push([tau,chartValue(impact,key)]);
  past.push([time,chartValue(current(),key)]);
  line(ctx,past.map(([t,v])=>[X(t),Y(v)]),colors.teal,2.2);
  line(ctx,[[X(time),T],[X(time),T+ph]],'#c49c61',1);dot(ctx,X(time),Y(chartValue(current(),key)),colors.amber,3.5);ctx.restore();
 }
 function draw() {
  if(!rows.length)return;dirty=false;
  const sections=Array.from($('r-rows').children),openCount=sections.filter(row=>row.open).length;
  if(openCount){
   const height=$('r-rows').getBoundingClientRect().height;
   const chartHeight=Math.min(116,Math.max(36,(height-sections.length*28-(sections.length-1)*5-openCount*35)/openCount));
   $('r-rows').style.setProperty('--r-chart-height',`${chartHeight}px`);
  }
  phase();
  for(const [key] of charts)series(`r-chart-${key}`,key);
  if($('r-zoom').open){if(zoomKey==='phase')phase('r-zoom-canvas');else series('r-zoom-canvas',zoomKey);}
  const currentRow=current(),t=Math.floor(time);
  $('r-time').value=time;fill($('r-time'));$('r-time-value').textContent=t;
  $('r-regime').textContent=jumpActive?'Shock: consumption jumps':different()?t<tau?anticipated?`Announced · policy in ${tau-t}`:`Shock in ${tau-t} periods`:'After the shock':'Initial economy';
  $('r-regime').classList.toggle('shocked',different()&&time>=tau);
  for(const [key] of charts)$(`r-value-${key}`).textContent=displayValue(chartValue(currentRow,key),key);
  for(const [id,v] of [['current-k',currentRow.k],['current-c',currentRow.c],['old-k',steady(before).k],['new-k',steady(after).k],['A',currentRow.A],['N',currentRow.N]])$(`r-${id}`).textContent=format(v);
  $('r-live-t').textContent=`t = ${t}`;
  const p=time<tau?before:after;$('r-growth').textContent=`γ = ${format(p.gamma)} · n = ${format(p.n)}`;
  $('r-step').disabled=time>=endTime;
 }
 function frame(now) {
  const elapsed=Math.max(0,Math.min(.1,(now-lastFrame)/1000));lastFrame=now;
  if(playing) {
   if(jumpActive){jumpProgress=Math.min(1,jumpProgress+elapsed/.8);if(jumpProgress>=1)jumpActive=false;}
   else {const next=Math.min(endTime,time+elapsed*+$('r-speed').value);if(hasJump()&&time<tau&&next>=tau){time=tau;jumpActive=true;jumpProgress=0;}else time=next;}
   dirty=true;if(time>=endTime)pause();
  }
  try {if(dirty&&!workspace.hidden)draw();}
  catch(error){pause();$('r-insight').textContent=`Could not draw the Ramsey graphs: ${error.message}`;console.error(error);}
  requestAnimationFrame(frame);
 }
 function openZoom(key) {
  zoomKey=key;const entry=charts.find(x=>x[0]===key);
  $('r-zoom-title').textContent=key==='phase'?'Phase diagram':entry[1];
  $('r-zoom-y').dataset.tex=key==='phase'?'c_t':entry[2];$('r-zoom-x').hidden=key!=='phase';
  typeset($('r-zoom'));$('r-zoom').showModal();dirty=true;
 }
 build();
 listen('r-play','click',()=>playing?pause():play());listen('r-zoom-play','click',()=>playing?pause():play());
 listen('r-replay','click',()=>{pause();time=0;play();});
 listen('r-step','click',()=>{pause();time=Math.min(endTime,Math.floor(time+1));dirty=true;});
 listen('r-time','input',e=>{pause();time=Math.max(0,Math.min(endTime,+e.target.value));dirty=true;});
 listen('r-before','click',()=>{mode='before';sync();});listen('r-after','click',()=>{mode='after';sync();});
 for(const [id,g,n] of [['r-growth-none',1,1],['r-growth-positive',1.02,1.01]])listen(id,'click',()=>change(()=>{const p=mode==='before'?before:after;p.gamma=g;p.n=n;},mode==='before'||anticipated?0:tau-1));
 listen('r-k0','change',e=>change(()=>{const k=+e.target.value;if(!(k>0&&k<=1000))throw Error('Initial capital must be between zero and 1000');k0=k;locked=false;},0));
 listen('r-steady','click',()=>change(()=>{if(before.tax===1)throw Error('100% tax has no positive initial steady state');locked=true;},0));
 listen('r-tau','change',e=>{const t=Math.max(1,Math.min(horizon-1,Math.round(+e.target.value)||20));change(()=>tau=t,t-1);});
 listen('r-horizon','change',e=>change(()=>{horizon=+e.target.value;tau=Math.min(tau,horizon-1);},0));
 listen('r-anticipated','click',()=>change(()=>anticipated=true,0));
 listen('r-unanticipated','click',()=>change(()=>anticipated=false,Math.min(time,tau-1)));
 listen('r-unstable','click',()=>{showUnstable=!showUnstable;sync();});
 listen('r-c0-deviation','input',e=>change(()=>consumptionDeviation=+e.target.value/100,0));
 listen('r-c0-restore','click',()=>change(()=>consumptionDeviation=0,0));
 const resetRamsey=()=>change(()=>{before={...RAMSEY_DEFAULTS};after={...RAMSEY_DEFAULTS};locked=true;mode='after';tau=20;horizon=160;anticipated=false;consumptionDeviation=0;showUnstable=false;},0);
 $('reset').addEventListener('click',event=>{if(workspace.hidden)return;event.preventDefault?.();event.stopImmediatePropagation?.();resetRamsey();},true);
 workspace.querySelectorAll('[data-r-preset]').forEach(button=>button.addEventListener('click',()=>{
  const accepted=change(()=>{
   after={...before};mode='after';
   switch(button.dataset.rPreset){
    case 'tax':after.tax=Math.min(1,before.tax+.25);break;
    case 'tax-cut':before.tax=Math.max(.25,before.tax);after={...before,tax:Math.max(0,before.tax-.25)};break;
    case 'patience':after.beta=Math.min(.995,before.beta+.02);break;
    case 'depreciation':after.delta=Math.min(.25,before.delta+.05);break;
    case 'share':after.alpha=Math.min(.65,before.alpha+.08);break;
   }
  },anticipated?0:tau-1);if(accepted)play();
 }));
 listen('r-phase-zoom','click',()=>openZoom('phase'));listen('r-zoom-close','click',()=>$('r-zoom').close());
 $('help').addEventListener('click',event=>{if(workspace.hidden)return;event.preventDefault?.();event.stopImmediatePropagation?.();$('r-model-dialog').showModal();},true);
 listen('r-help-close','click',()=>$('r-model-dialog').close());
 listen('r-panel-hide','click',()=>{workspace.classList.add('controls-hidden');$('r-panel-show').hidden=false;dirty=true;});
 listen('r-panel-show','click',()=>{workspace.classList.remove('controls-hidden');$('r-panel-show').hidden=true;dirty=true;});
 document.addEventListener('macro-model-change',event=>{if(event.detail.model!=='ramsey')pause();dirty=true;});
 $('help-footer').addEventListener('click',e=>{if(!workspace.hidden){e.stopImmediatePropagation();$('r-model-dialog').showModal();}},true);
 if(window.ResizeObserver){const observer=new ResizeObserver(()=>dirty=true);observer.observe(workspace);observer.observe($('r-zoom'));}
 window.addEventListener('resize',()=>dirty=true);
 recompute();sync();document.body.dataset.ramseyStatus='ready';requestAnimationFrame(frame);
}
function startRamsey() {
 try { initializeRamsey(); }
 catch(error) {
  document.body.dataset.ramseyStatus='error';
  const status=document.getElementById('r-insight');
  if(status)status.textContent=`Ramsey could not start: ${error.message}`;
  console.error(error);
 }
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startRamsey,{once:true});
else startRamsey();

})();
